#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           12
#bspc config top_padding		36
#bspc config right_padding 	 15
#bspc config bottom_padding 	 15
#bspc config left_padding 	 15
bspc config top_monocle_padding   -27
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focused_border_color "$(sed '2q;d' /home/nimz/.cache/wal/colors)"

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
bspc rule -a Surf state=tiled
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

#  double borders
# needs chwb2 from wmutils/opt

# outer='0xf2f2f2'   # outer
# inner1='0x89bbd2'  # focused
# inner2='0xdde0e3'  # normal

# trap 'bspc config border_width 0; kill -9 -$$' INT TERM

# targets() {
# 	case $1 in
# 		focused) bspc query -N -n .local.focused.\!fullscreen;;
# 		normal)  bspc query -N -n .\!focused.\!fullscreen
# 	esac
# }
# bspc config border_width 8 #4

# draw() { $HOME/src/opt/chwb2 -I "$inner" -O "$outer" -i "2" -o "5" $*; }

# # initial draw, and then subscribe to events
# { echo; bspc subscribe node_geometry node_focus; } |
# 	while read -r _; do
# 		[ "$v" ] || v='abcdefg'
# 		inner=$inner1 draw $(targets focused)
# 		inner=$inner2 draw $(targets  normal)
# 	done
